Fix Detekt CI (#91)
Detekt will be relative to Heroku Gradle project, not repo root, but GitHub code scanning is based on repo root.

diff --git a/.github/workflows/Heroku.yml b/.github/workflows/Heroku.yml
--- a/.github/workflows/Heroku.yml
+++ b/.github/workflows/Heroku.yml
@@ -149,30 +149,24 @@ jobs:
         working-directory: artifacts
         run: ls -R
 
-      - name: Fix detekt paths.
-        run: >
-          sed -re 's!"uri": "${{ github.workspace }}!"uri": "file://${{ github.workspace }}!g'\
-              <artifacts/build/reports/detekt/detekt.sarif\
-              >artifacts/build/reports/detekt/detekt-fixed.sarif
+      - name: Fail if there is no report or warnings.
+        working-directory: artifacts
+        run: |
+          if [ ! -f 'build/reports/detekt/detekt.txt' ]; then # -f: Path exists and is regular file.
+            echo "Detekt report file does not exist"
+            exit 2
+          fi
+          if [ -s 'build/reports/detekt/detekt.txt' ]; then # -s: File has contents.
+            echo "There were detekt failures."
+            exit 3
+          fi
 
       - name: Publish Detekt Results
         uses: github/codeql-action/upload-sarif@v1
         if: success() || failure()
         with:
           checkout_path: ${{ github.workspace }}
-          sarif_file: artifacts/build/reports/detekt/detekt-fixed.sarif
-
-      - name: Fail if there are warnings or no report.
-        working-directory: artifacts
-        run: |
-          if [ ! -f 'detekt.txt' ]; then # -f: Path exists and is regular file.
-            echo "File does not exist"
-            exit 2
-          fi
-          if [ -s 'detekt.txt' ]; then # -s: File has contents.
-            echo "There were detekt failures."
-            exit 3
-          fi
+          sarif_file: artifacts/build/reports/detekt/detekt.sarif
 
   # Separate job for parsing the XML output,
   # since the matrix runs on multiple machines.
