Disable testing and report separately

diff --git a/.github/workflows/Heroku.yml b/.github/workflows/Heroku.yml
--- a/.github/workflows/Heroku.yml
+++ b/.github/workflows/Heroku.yml
@@ -55,16 +55,17 @@ jobs:
           restore-keys: |
             ${{ runner.os }}-gradle-${{ env.GRADLE_VERSION }}-
 
+
       - name: Dump Heroku Dependencies.
         working-directory: Heroku
-        run: (./gradlew --no-daemon --no-build-cache --stacktrace allDependencies | tee build/dependencies.txt) || true
+        run: ./gradlew --no-daemon --no-build-cache --stacktrace allDependencies | tee dependencies.txt
 
       - name: Upload "Heroku Dependencies".
         if: success() || failure()
         uses: actions/upload-artifact@v2
         with:
           name: Heroku Dependencies
-          path: ${{ github.workspace }}/Heroku/build/dependencies.txt
+          path: ${{ github.workspace }}/Heroku/dependencies.txt
 
 
       - name: Check Heroku.
@@ -78,27 +79,22 @@ jobs:
           name: Heroku Detekt Results
           path: ${{ github.workspace }}/Heroku/**/build/reports/detekt/detekt.*
 
-      - uses: github/codeql-action/upload-sarif@v1
-        if: success() || failure()
-        with:
-          sarif_file: ${{ github.workspace }}/Heroku/build/reports/detekt/detekt.sarif
+
+#      - name: Build Heroku.
+#        working-directory: Heroku
+#        run: ./gradlew --no-daemon --no-build-cache --stacktrace assemble testClasses
 
 
-      - name: Build Heroku.
-        working-directory: Heroku
-        run: ./gradlew --no-daemon --no-build-cache --stacktrace assemble testClasses
-
-
-      - name: Test Heroku.
-        working-directory: Heroku
-        run: >
-          ./gradlew
-          --no-daemon
-          --no-build-cache
-          --stacktrace
-          tests :allTestsReport
-          -Pnet.twisterrob.build.verboseReports=true
-          -Pnet.twisterrob.build.testConcurrencyOverride=PerSuite
+#      - name: Test Heroku.
+#        working-directory: Heroku
+#        run: >
+#          ./gradlew
+#          --no-daemon
+#          --no-build-cache
+#          --stacktrace
+#          tests :allTestsReport
+#          -Pnet.twisterrob.build.verboseReports=true
+#          -Pnet.twisterrob.build.testConcurrencyOverride=PerSuite
 
       - name: Upload "Heroku Test Results XMLs".
         if: success() || failure()
@@ -128,6 +124,42 @@ jobs:
           rm -f  ~/.gradle/caches/modules-2/gc.properties
           rm -fr ~/.gradle/caches/*/plugin-resolution/
 
+  # Separate job for parsing the output, since there are multiple steps when running checks.
+  publish-detekt-results-gradle:
+    name: 2 📢 Publish Detekt Results
+    runs-on: ubuntu-latest
+    needs: check-gradle
+    # The dependency job might be skipped, we don't need to run this job then.
+    if: success() || failure()
+    # Should finish under 2 minutes on success, so give it a big buffer in case failures take more time.
+    timeout-minutes: 5
+
+    steps:
+      - name: Download Artifacts
+        uses: actions/download-artifact@v2
+        with:
+          path: artifacts
+
+      #- name: Display structure of downloaded files
+      #  run: ls -R
+      #  working-directory: artifacts
+
+      - name: Publish Detekt Results
+      - uses: github/codeql-action/upload-sarif@v1
+        if: success() || failure()
+        with:
+          checkout_path: ${{ github.workspace }}
+          sarif_file: artifacts/Heroku Detekt Results/Heroku/build/reports/detekt/detekt.sarif
+
+      - name: Fail if there are warnings or no report.
+        run: >
+          function fail {
+              echo "$1" >&2
+              exit 1
+          }
+          test -f 'artifacts/Heroku Detekt Results/Heroku/build/reports/detekt/detekt.sarif' || fail "File does not exist"
+          test -s 'artifacts/Heroku Detekt Results/Heroku/build/reports/detekt/detekt.sarif' && fail "There were detekt failures."
+
   # Separate job for parsing the XML output, since the matrix runs on multiple machines.
   publish-test-results-gradle:
     name: 2 📢 Publish Tests Results
@@ -156,6 +188,7 @@ jobs:
           report_individual_runs: true
           test_changes_limit: 0
           files: artifacts/Heroku Test Results XMLs/**/*.xml
+
   check-npm:
     name: 1 🔨 Build & Check (NPM)
     # https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md
