Fix failure detection

diff --git a/.github/workflows/Heroku.yml b/.github/workflows/Heroku.yml
--- a/.github/workflows/Heroku.yml
+++ b/.github/workflows/Heroku.yml
@@ -165,8 +165,14 @@ jobs:
       - name: Fail if there are warnings or no report.
         working-directory: artifacts
         run: |
-          test -f 'build/reports/detekt/detekt.txt' || (echo "File does not exist"; exit 1)
-          test -s 'build/reports/detekt/detekt.txt' && (echo "There were detekt failures."; exit 1)
+          if [ ! -f 'detekt.txt' ]; then # -f: Path exists and is regular file.
+            echo "File does not exist"
+            exit 2
+          fi
+          if [ -s 'detekt.txt' ]; then # -s: File has contents.
+            echo "There were detekt failures."
+            exit 3
+          fi
 
   # Separate job for parsing the XML output,
   # since the matrix runs on multiple machines.
